#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul  9 21:39:45 2019

@author: jesusrodriguez
"""

import numpy as np
import matplotlib.pyplot as plt



x = np.linspace(-2*np.pi, 2*np.pi, 400)
#breakpoint()

y = np.tanh(x)



plt.plot(x, y)

    